// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service contains application use cases. The Wails bridge delegates to this
 * type, keeping the UI unaware of SQLite and keeping business writes ordered:
 * Go -> SQLite -> fresh query -> Zustand.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function AddFollowup(input: domain$0.PlanFollowupInput): $CancellablePromise<domain$0.PlanFollowup> {
    return $Call.ByID(3871751298, input);
}

export function AppInfo(): $CancellablePromise<domain$0.AppInfo> {
    return $Call.ByID(26884706);
}

export function ArchiveAnchor(id: number): $CancellablePromise<void> {
    return $Call.ByID(4096324998, id);
}

export function BackupDirectory(): $CancellablePromise<string> {
    return $Call.ByID(910881688);
}

export function ChangeGoalStatus(id: number, status: string): $CancellablePromise<domain$0.StageGoal> {
    return $Call.ByID(1625547102, id, status);
}

export function ChangeIssueStatus(id: number, status: string): $CancellablePromise<domain$0.AnchorIssue> {
    return $Call.ByID(1161417260, id, status);
}

export function ChangePlanStatus(id: number, status: string): $CancellablePromise<domain$0.ImprovementPlan> {
    return $Call.ByID(1417765390, id, status);
}

export function CreateAnchor(input: domain$0.AnchorInput): $CancellablePromise<domain$0.Anchor> {
    return $Call.ByID(2853986382, input);
}

export function CreateEvent(input: domain$0.AnchorEventInput): $CancellablePromise<domain$0.AnchorEvent> {
    return $Call.ByID(856116117, input);
}

export function CreateGoal(input: domain$0.StageGoalInput): $CancellablePromise<domain$0.StageGoal> {
    return $Call.ByID(457835224, input);
}

export function CreateIssue(input: domain$0.AnchorIssueInput): $CancellablePromise<domain$0.AnchorIssue> {
    return $Call.ByID(1868053606, input);
}

export function CreatePlan(input: domain$0.ImprovementPlanInput): $CancellablePromise<domain$0.ImprovementPlan> {
    return $Call.ByID(1010931952, input);
}

export function CreateReview(input: domain$0.OperationReviewInput): $CancellablePromise<domain$0.OperationReview> {
    return $Call.ByID(3625674063, input);
}

export function CreateSession(input: domain$0.LiveSessionInput): $CancellablePromise<domain$0.LiveSession> {
    return $Call.ByID(80977953, input);
}

export function DataDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1135147374);
}

export function DeleteEvent(id: number): $CancellablePromise<void> {
    return $Call.ByID(1642945476, id);
}

export function DeleteFollowup(id: number): $CancellablePromise<void> {
    return $Call.ByID(3502643596, id);
}

export function DeletePlan(id: number): $CancellablePromise<void> {
    return $Call.ByID(4008518815, id);
}

export function DeleteSession(id: number): $CancellablePromise<void> {
    return $Call.ByID(1593675880, id);
}

export function ExportBackup(): $CancellablePromise<domain$0.BackupExport> {
    return $Call.ByID(2197106471);
}

export function GetAnchor(id: number): $CancellablePromise<domain$0.Anchor> {
    return $Call.ByID(501128680, id);
}

export function GetAnchorDetail(id: number): $CancellablePromise<domain$0.AnchorDetail> {
    return $Call.ByID(3872909513, id);
}

export function GetAnchorTrend(anchorID: number, days: number): $CancellablePromise<domain$0.TrendPoint[] | null> {
    return $Call.ByID(2236511423, anchorID, days);
}

export function GetAnchorTrendRange(anchorID: number, startDate: string, endDate: string): $CancellablePromise<domain$0.TrendPoint[] | null> {
    return $Call.ByID(923967156, anchorID, startDate, endDate);
}

export function GetDashboard(staleDays: number): $CancellablePromise<domain$0.Dashboard> {
    return $Call.ByID(1105502559, staleDays);
}

export function GetEvent(id: number): $CancellablePromise<domain$0.AnchorEvent> {
    return $Call.ByID(1732566563, id);
}

export function GetFollowup(id: number): $CancellablePromise<domain$0.PlanFollowup> {
    return $Call.ByID(2463740633, id);
}

export function GetGoal(id: number): $CancellablePromise<domain$0.StageGoal> {
    return $Call.ByID(3002786882, id);
}

export function GetIssue(id: number): $CancellablePromise<domain$0.AnchorIssue> {
    return $Call.ByID(3285190508, id);
}

export function GetPlan(id: number): $CancellablePromise<domain$0.ImprovementPlan> {
    return $Call.ByID(2424447190, id);
}

export function GetReview(id: number): $CancellablePromise<domain$0.OperationReview> {
    return $Call.ByID(2388347733, id);
}

export function GetSession(id: number): $CancellablePromise<domain$0.LiveSession> {
    return $Call.ByID(851877387, id);
}

export function ImportBackup(archiveBase64: string): $CancellablePromise<void> {
    return $Call.ByID(675150872, archiveBase64);
}

export function ListAnchors(filter: domain$0.AnchorFilter): $CancellablePromise<domain$0.AnchorPage> {
    return $Call.ByID(937386855, filter);
}

export function ListEvents(anchorID: number): $CancellablePromise<domain$0.AnchorEvent[] | null> {
    return $Call.ByID(1955332594, anchorID);
}

export function ListFollowups(planID: number): $CancellablePromise<domain$0.PlanFollowup[] | null> {
    return $Call.ByID(21326892, planID);
}

export function ListGoals(anchorID: number): $CancellablePromise<domain$0.StageGoal[] | null> {
    return $Call.ByID(1592764561, anchorID);
}

export function ListIssues(anchorID: number, status: string): $CancellablePromise<domain$0.AnchorIssue[] | null> {
    return $Call.ByID(2532814575, anchorID, status);
}

export function ListPlans(anchorID: number, status: string): $CancellablePromise<domain$0.ImprovementPlan[] | null> {
    return $Call.ByID(481332121, anchorID, status);
}

export function ListReviews(anchorID: number): $CancellablePromise<domain$0.OperationReview[] | null> {
    return $Call.ByID(2673098964, anchorID);
}

export function ListSessionPage(filter: domain$0.SessionFilter): $CancellablePromise<domain$0.SessionPage> {
    return $Call.ByID(3396702498, filter);
}

export function ListSessions(anchorID: number): $CancellablePromise<domain$0.LiveSession[] | null> {
    return $Call.ByID(3272772086, anchorID);
}

export function ListTagNames(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3734818711);
}

export function LogDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3361204886);
}

export function OpenDataDirectory(): $CancellablePromise<void> {
    return $Call.ByID(3525871706);
}

export function OpenLogDirectory(): $CancellablePromise<void> {
    return $Call.ByID(2975398258);
}

export function Search(query: string): $CancellablePromise<domain$0.SearchResult[] | null> {
    return $Call.ByID(1372877855, query);
}

export function UpdateAnchor(id: number, input: domain$0.AnchorInput): $CancellablePromise<domain$0.Anchor> {
    return $Call.ByID(3700979119, id, input);
}

export function UpdateEvent(id: number, input: domain$0.AnchorEventInput): $CancellablePromise<domain$0.AnchorEvent> {
    return $Call.ByID(2099876650, id, input);
}

export function UpdateFollowup(id: number, input: domain$0.PlanFollowupInput): $CancellablePromise<domain$0.PlanFollowup> {
    return $Call.ByID(3622568222, id, input);
}

export function UpdateGoal(id: number, input: domain$0.StageGoalInput): $CancellablePromise<domain$0.StageGoal> {
    return $Call.ByID(3217615025, id, input);
}

export function UpdateIssue(id: number, input: domain$0.AnchorIssueInput): $CancellablePromise<domain$0.AnchorIssue> {
    return $Call.ByID(2973440213, id, input);
}

export function UpdatePlan(id: number, input: domain$0.ImprovementPlanInput): $CancellablePromise<domain$0.ImprovementPlan> {
    return $Call.ByID(2415880549, id, input);
}

export function UpdateReview(id: number, input: domain$0.OperationReviewInput): $CancellablePromise<domain$0.OperationReview> {
    return $Call.ByID(3380152054, id, input);
}

export function UpdateSession(id: number, input: domain$0.LiveSessionInput): $CancellablePromise<domain$0.LiveSession> {
    return $Call.ByID(849639762, id, input);
}
