package main

import (
	"embed"
	"log"

	appservice "github.com/hicbowen/livemate/internal/application"
	"github.com/hicbowen/livemate/internal/bridge/wails"
	"github.com/hicbowen/livemate/internal/config"
	"github.com/hicbowen/livemate/internal/infrastructure/sqlite"
	"github.com/hicbowen/livemate/internal/platform"
	"github.com/wailsapp/wails/v3/pkg/application"
)

// Wails embeds the production frontend generated by Vite.
//
//go:embed all:frontend/dist
var assets embed.FS

func main() {
	paths, err := config.Resolve()
	if err != nil {
		log.Fatalf("播伴初始化失败：%v", err)
	}
	logger, err := platform.NewLogger(paths)
	if err != nil {
		log.Fatalf("播伴日志初始化失败：%v", err)
	}
	defer logger.Close()
	logger.Printf("应用启动 version=%s data_dir=%s", "1.0.0", paths.DataDir)

	store, err := sqlite.Open(paths, logger)
	if err != nil {
		logger.Printf("数据库初始化失败：%v", err)
		log.Fatal(err)
	}
	defer store.Close()

	service := appservice.NewService(store)
	app := application.New(application.Options{
		Name:        "播伴",
		Description: "主播运营管理与 AI 辅助工具",
		Services: []application.Service{
			application.NewService(wails.NewService(service)),
		},
		Assets: application.AssetOptions{
			Handler: application.AssetFileServerFS(assets),
		},
		Mac: application.MacOptions{
			ApplicationShouldTerminateAfterLastWindowClosed: true,
		},
	})

	app.Window.NewWithOptions(application.WebviewWindowOptions{
		Title:  "播伴",
		Width:  1280,
		Height: 800,
		Mac: application.MacWindow{
			InvisibleTitleBarHeight: 50,
			Backdrop:                application.MacBackdropTranslucent,
			TitleBar:                application.MacTitleBarHiddenInset,
		},
		BackgroundColour: application.NewRGB(247, 249, 252),
		URL:              "/",
	})

	err = app.Run()
	if err != nil {
		logger.Printf("Wails backend error：%v", err)
		log.Fatal(err)
	}
}
