// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Anchor {
    "id": number;
    "name": string;
    "nickname": string;
    "platform": string;
    "platform_uid": string;
    "account_name": string;
    "category": string;
    "gender": string;
    "age": number | null;
    "joined_at": string | null;
    "operator_name": string;
    "stage": string;
    "attention_level": string;
    "status": string;
    "notes": string;
    "tags": string[] | null;
    "created_at": string;
    "updated_at": string;
    "deleted_at": string | null;
}

export interface AnchorDetail {
    "anchor": Anchor;
    "sessions": LiveSession[] | null;
    "reviews": OperationReview[] | null;
    "issues": AnchorIssue[] | null;
    "plans": ImprovementPlan[] | null;
    "followups": PlanFollowup[] | null;
    "goals": StageGoal[] | null;
    "events": AnchorEvent[] | null;
    "status_changes": StatusChange[] | null;
    "trend": TrendPoint[] | null;
}

export interface AnchorEvent {
    "id": number;
    "anchor_id": number;
    "event_date": string;
    "event_type": string;
    "title": string;
    "content": string;
    "live_session_id": number | null;
    "created_at": string;
    "updated_at": string;
}

export interface AnchorEventInput {
    "anchor_id": number;
    "event_date": string;
    "event_type": string;
    "title": string;
    "content": string;
    "live_session_id": number | null;
}

export interface AnchorFilter {
    "query": string;
    "stage": string;
    "status": string;
    "attention_level": string;
    "tag": string;
    "page": number;
    "page_size": number;
    "sort_by": string;
    "sort_desc": boolean;
}

export interface AnchorInput {
    "name": string;
    "nickname": string;
    "platform": string;
    "platform_uid": string;
    "account_name": string;
    "category": string;
    "gender": string;
    "age": number | null;
    "joined_at": string | null;
    "operator_name": string;
    "stage": string;
    "attention_level": string;
    "status": string;
    "notes": string;
    "tags": string[] | null;
}

export interface AnchorIssue {
    "id": number;
    "anchor_id": number;
    "review_id": number | null;
    "title": string;
    "category": string;
    "description": string;
    "evidence": string;
    "cause_hypothesis": string;
    "priority": string;
    "status": string;
    "discovered_at": string;
    "resolved_at": string | null;
    "plan_count": number;
    "created_at": string;
    "updated_at": string;
}

export interface AnchorIssueInput {
    "anchor_id": number;
    "review_id": number | null;
    "title": string;
    "category": string;
    "description": string;
    "evidence": string;
    "cause_hypothesis": string;
    "priority": string;
    "status": string;
    "discovered_at": string;
}

export interface AnchorListItem {
    "id": number;
    "name": string;
    "nickname": string;
    "platform": string;
    "platform_uid": string;
    "account_name": string;
    "category": string;
    "gender": string;
    "age": number | null;
    "joined_at": string | null;
    "operator_name": string;
    "stage": string;
    "attention_level": string;
    "status": string;
    "notes": string;
    "tags": string[] | null;
    "created_at": string;
    "updated_at": string;
    "deleted_at": string | null;
    "last_session_date": string | null;
    "last_activity_date": string | null;
    "last_7_duration_minutes": number;
    "last_7_revenue_cents": number;
    "last_7_followers_gained": number;
    "pending_issue_count": number;
    "active_plan_count": number;
}

export interface AnchorPage {
    "page": PageInfo;
    "items": AnchorListItem[] | null;
}

export interface AnomalyCandidate {
    "id": string;
    "rule": string;
    "title": string;
    "evidence": string;
    "detected_at": string;
    "related_session_ids": number[] | null;
}

export interface AnomalyDecisionInput {
    "anchor_id": number;
    "anomaly_id": string;
    "detected_at": string;
    "decision": string;
}

export interface AppInfo {
    "name": string;
    "project": string;
    "app_id": string;
    "version": string;
    "description": string;
    "data_dir": string;
    "database_path": string;
    "log_dir": string;
    "backup_dir": string;
}

export interface BackupExport {
    "file_name": string;
    "path": string;
    "archive_base64": string;
    "exported_at": string;
}

export interface DailyData {
    "session_date": string;
    "rows": DailyDataRow[] | null;
}

/**
 * DailyDataBatchInput is the file-import boundary. All dated batches are
 * committed in one transaction so a failed file cannot leave earlier dates
 * partially imported.
 */
export interface DailyDataBatchInput {
    "source": string;
    "batches": DailyDataInput[] | null;
}

export interface DailyDataBatchSaveResult {
    "saved_count": number;
    "created_count": number;
    "updated_count": number;
    "dates": string[] | null;
}

export interface DailyDataInput {
    "session_date": string;
    "source": string;
    "rows": DailySessionInput[] | null;
}

/**
 * DailyDataQuery is the compact view used by the daily operations workbench.
 * It deliberately exposes only the fields that operators enter repeatedly;
 * the full LiveSession model remains available from the anchor detail page.
 */
export interface DailyDataQuery {
    "session_date": string;
    "query": string;
}

export interface DailyDataRow {
    "anchor_id": number;
    "nickname": string;
    "platform": string;
    "stage": string;
    "status": string;
    "session_id": number | null;
    "duration_minutes": number | null;
    "views": number | null;
    "avg_online": number | null;
    "avg_stay_seconds": number | null;
    "followers_gained": number | null;
    "revenue_cents": number | null;
}

export interface DailyDataSaveResult {
    "session_date": string;
    "saved_count": number;
    "created_count": number;
    "updated_count": number;
    "sessions": LiveSession[] | null;
}

export interface DailySessionInput {
    "anchor_id": number;
    "duration_minutes": number | null;
    "views": number | null;
    "avg_online": number | null;
    "avg_stay_seconds": number | null;
    "followers_gained": number | null;
    "revenue_cents": number | null;
    "clear_fields"?: string[] | null;
}

export interface Dashboard {
    "generated_at": string;
    "today": string;
    "anchor_count": number;
    "today_live_anchor_count": number;
    "today_not_live_anchor_count": number;
    "today_duration_minutes": number | null;
    "today_revenue_cents": number | null;
    "today_followers_gained": number | null;
    "focus_anchors": FocusAnchor[] | null;
    "pending_issues": IssueSummary[] | null;
    "active_plans": PlanSummary[] | null;
    "stale_plans": PlanSummary[] | null;
    "expiring_goals": ExpiringGoal[] | null;
    "stale_anchors": StaleAnchor[] | null;
    "stale_days": number;
}

export interface ExpiringGoal {
    "id": number;
    "anchor_id": number;
    "anchor_nickname": string;
    "title": string;
    "end_date": string;
    "days_remaining": number;
}

export interface FocusAnchor {
    "anchor_id": number;
    "nickname": string;
    "stage": string;
    "attention_level": string;
    "attention_reason": string;
    "last_session_date": string | null;
    "recent_change_note": string;
}

export interface GoalMetric {
    "id": number;
    "goal_id": number;
    "metric_name": string;
    "baseline_value": number | null;
    "target_value": number | null;
    "metric_unit": string;
    "created_at": string;
}

export interface GoalMetricInput {
    "metric_name": string;
    "baseline_value": number | null;
    "target_value": number | null;
    "metric_unit": string;
}

/**
 * ImportTable is the neutral table shape shared by the spreadsheet parser
 * and the frontend mapping/validation workflow.
 */
export interface ImportTable {
    "file_name": string;
    "sheet_name": string;
    "headers": string[] | null;
    "rows": (string[] | null)[] | null;
}

export interface ImprovementPlan {
    "id": number;
    "anchor_id": number;
    "issue_id": number;
    "title": string;
    "objective": string;
    "actions": string;
    "metric_name": string;
    "baseline_value": number | null;
    "target_value": number | null;
    "metric_unit": string;
    "start_date": string;
    "expected_end_date": string | null;
    "priority": string;
    "status": string;
    "result_summary": string;
    "completed_at": string | null;
    "last_followup_date": string | null;
    "current_metric_value": number | null;
    "followup_count": number;
    "created_at": string;
    "updated_at": string;
}

export interface ImprovementPlanInput {
    "anchor_id": number;
    "issue_id": number;
    "title": string;
    "objective": string;
    "actions": string;
    "metric_name": string;
    "baseline_value": number | null;
    "target_value": number | null;
    "metric_unit": string;
    "start_date": string;
    "expected_end_date": string | null;
    "priority": string;
    "status": string;
    "result_summary": string;
}

export interface IssueSummary {
    "id": number;
    "anchor_id": number;
    "anchor_nickname": string;
    "title": string;
    "category": string;
    "priority": string;
    "status": string;
    "discovered_at": string;
}

export interface LiveSession {
    "id": number;
    "anchor_id": number;
    "session_date": string;
    "started_at": string | null;
    "ended_at": string | null;
    "duration_minutes": number | null;
    "duration_override": boolean;
    "views": number | null;
    "peak_online": number | null;
    "avg_online": number | null;
    "avg_stay_seconds": number | null;
    "likes": number | null;
    "comments": number | null;
    "comment_users": number | null;
    "shares": number | null;
    "followers_before": number | null;
    "followers_after": number | null;
    "followers_gained": number | null;
    "revenue_cents": number | null;
    "payer_count": number | null;
    "gift_user_count": number | null;
    "pk_count": number | null;
    "pk_win_count": number | null;
    "pk_revenue_cents": number | null;
    "operator_name": string;
    "is_abnormal": boolean;
    "abnormal_note": string;
    "source": string;
    "notes": string;
    "metrics": SessionMetrics;
    "created_at": string;
    "updated_at": string;
}

export interface LiveSessionInput {
    "anchor_id": number;
    "session_date": string;
    "started_at": string | null;
    "ended_at": string | null;
    "duration_minutes": number | null;
    "duration_override": boolean;
    "views": number | null;
    "peak_online": number | null;
    "avg_online": number | null;
    "avg_stay_seconds": number | null;
    "likes": number | null;
    "comments": number | null;
    "comment_users": number | null;
    "shares": number | null;
    "followers_before": number | null;
    "followers_after": number | null;
    "followers_gained": number | null;
    "revenue_cents": number | null;
    "payer_count": number | null;
    "gift_user_count": number | null;
    "pk_count": number | null;
    "pk_win_count": number | null;
    "pk_revenue_cents": number | null;
    "operator_name": string;
    "is_abnormal": boolean;
    "abnormal_note": string;
    "source": string;
    "notes": string;
}

export interface OperationReview {
    "id": number;
    "anchor_id": number;
    "live_session_id": number | null;
    "review_date": string;
    "summary": string;
    "strengths": string;
    "observations": string;
    "conclusion": string;
    "created_at": string;
    "updated_at": string;
}

export interface OperationReviewInput {
    "anchor_id": number;
    "live_session_id": number | null;
    "review_date": string;
    "summary": string;
    "strengths": string;
    "observations": string;
    "conclusion": string;
}

export interface PageInfo {
    "page": number;
    "page_size": number;
    "total": number;
    "total_pages": number;
}

export interface PeriodComparison {
    "period_days": number;
    "previous_start_date": string;
    "previous_end_date": string;
    "current_start_date": string;
    "current_end_date": string;
    "metrics": PeriodComparisonMetric[] | null;
}

export interface PeriodComparisonMetric {
    "metric_name": string;
    "label": string;
    "unit": string;
    "previous_value": number | null;
    "current_value": number | null;
    "change_rate": number | null;
}

/**
 * PlanEffectComparison compares the last three available sessions before a
 * plan started with the first three sessions after it started. It is a
 * compact, factual signal; it does not claim that the plan caused the change.
 */
export interface PlanEffectComparison {
    "plan_id": number;
    "metric_name": string;
    "metric_unit": string;
    "baseline_value": number | null;
    "target_value": number | null;
    "current_value": number | null;
    "current_change": number | null;
    "current_change_rate": number | null;
    "before_count": number;
    "after_count": number;
    "before_average": number | null;
    "after_average": number | null;
    "before_after_change": number | null;
    "before_after_rate": number | null;
}

export interface PlanFollowup {
    "id": number;
    "plan_id": number;
    "anchor_id": number;
    "live_session_id": number | null;
    "followup_date": string;
    "execution_status": string;
    "execution_note": string;
    "metric_value": number | null;
    "metric_change": number | null;
    "metric_change_rate": number | null;
    "effect": string;
    "effect_note": string;
    "next_action": string;
    "created_at": string;
    "updated_at": string;
}

export interface PlanFollowupInput {
    "plan_id": number;
    "anchor_id": number;
    "live_session_id": number | null;
    "followup_date": string;
    "execution_status": string;
    "execution_note": string;
    "metric_value": number | null;
    "effect": string;
    "effect_note": string;
    "next_action": string;
}

export interface PlanSummary {
    "id": number;
    "anchor_id": number;
    "anchor_nickname": string;
    "title": string;
    "status": string;
    "start_date": string;
    "last_followup_date": string | null;
    "current_metric_value": number | null;
    "metric_unit": string;
    "days_active": number;
    "days_since_followup": number;
}

export interface SearchResult {
    "kind": string;
    "id": number;
    "anchor_id": number;
    "anchor_nickname": string;
    "title": string;
    "subtitle": string;
}

/**
 * SessionFilter keeps potentially large session history paged at the
 * application boundary. The anchor detail response only carries the recent
 * window needed for its overview.
 */
export interface SessionFilter {
    "anchor_id": number;
    "page": number;
    "page_size": number;
}

export interface SessionMetrics {
    "revenue_per_hour": number | null;
    "followers_per_hour": number | null;
    "followers_per_1000_views": number | null;
    "payer_rate": number | null;
    "comment_user_rate": number | null;
    "pk_win_rate": number | null;
}

export interface SessionPage {
    "page": PageInfo;
    "items": LiveSession[] | null;
}

export interface StageGoal {
    "id": number;
    "anchor_id": number;
    "title": string;
    "start_date": string;
    "end_date": string;
    "description": string;
    "status": string;
    "metrics": GoalMetric[] | null;
    "created_at": string;
    "updated_at": string;
}

export interface StageGoalInput {
    "anchor_id": number;
    "title": string;
    "start_date": string;
    "end_date": string;
    "description": string;
    "status": string;
    "metrics": GoalMetricInput[] | null;
}

export interface StaleAnchor {
    "anchor_id": number;
    "nickname": string;
    "stage": string;
    "status": string;
    "last_session_date": string | null;
    "days_since_live": number;
}

/**
 * StatusChange is an audit entry used by the anchor timeline. Status history
 * is recorded by SQLite triggers so changes made through any application use
 * case are visible without relying on the frontend to remember old values.
 */
export interface StatusChange {
    "id": number;
    "anchor_id": number;
    "entity_type": string;
    "entity_id": number;
    "entity_title": string;
    "status": string;
    "changed_at": string;
}

/**
 * TodoTask is the persisted unit used by the daily task page. Tasks are
 * intentionally scoped to a calendar date; the frontend can move or copy a
 * task by replacing the dated snapshot through the application service.
 */
export interface TodoTask {
    "id": string;
    "text": string;
    "completed": boolean;
    "time_range"?: string[] | null;
    "start_reminder_enabled": boolean;
}

export interface TrendPoint {
    "date": string;
    "duration_minutes": number | null;
    "avg_online": number | null;
    "avg_stay_seconds": number | null;
    "followers_gained": number | null;
    "revenue_cents": number | null;
    "event_count": number;
}
